### PR TITLE
Resizing clothing images on catalogue to fit equally

### PR DESCRIPTION
**Pull request by BrenMurrell**
Creating and equal thumbnail sizing solution for clothing catalogue

This solves issue #62 (see that issue for more information)

### CODE REVIEW

**Comment by BrenMurrell** [comment]
Just reviewed the single failing test. Not sure what's going on there? Not particularly clued up on testing though!

**Comment by Gloobywerts** [comment]
@BrenMurrell I'll have a look at the failing test.

**Comment by BrenMurrell** [comment]
Cheers @Gloobywerts! If you look at the history it showed up when we added the (unrelated) hamburger menu

**Comment by Gloobywerts** [comment]
@BrenMurrell @beverley-walter I'm not sure how the test was passing to begin with. I'm on a Windows at the moment, and having trouble getting it set up. But I think the issue is with this line: https://github.com/EDA-Gurgl/gurgl/blob/dev/test/client/renderClothing.test.js#L75

It should read t.is(item.props.children[1].props.children[0].props.children, 'test')

**Comment by Gloobywerts** [comment]
Sorry the numbers should be 2 and 0. Looks like a random <br /> was removed at some point breaking the children indexes

**Comment by BrenMurrell** [comment]
Magic. Will try. Sorry forgot to mention I couldn't get it working on
windows AT ALL. Ended up setting up a dual boot Ubuntu install. Problem
seems to be Sodium which is a package the EDA team added to handle auth.

**Comment by Gloobywerts** [comment]
Yeah I had the same issue with Sodium! Must work on Windows

**Comment by beverley-walter** [comment]
Hiya :) Do you and J-unit have email addresses you'd like me to use for the new Gurgl slack channel? 
Just went to a SoT git masterclass and actually felt like a master! woop-woop!

**Pull request merged**
